[package]
name = "hello"
version = "0.1.0"
authors = ["Calvin Brown <cab025@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azure-functions = "0.11.0"
