// WARNING: This file is regenerated by the `cargo func new` command.

mod hello;
mod hello_from_rust;

// Export the Azure Functions here.
azure_functions::export! {
    hello::hello,
    hello_from_rust::hello_from_rust,
}
